RAILS/VIPsystem/config/routes.rb
Rails.application.routes.draw do
  root 'people#index'
  resources :people
  post "people/:id/edit" => "people#update"
  post "people/new" => "people#create"

end

RAILS/VIPsystem/app/models/people.rb
class People < ActiveRecord::Base
	validates :name, :cpf, :borned, :office, presence: true

	before_save do
		self.security.gsub!(/[\[\]\"]/,"") if attribute_present?("security")
	end
end

RAILS/VIPsystem/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

RAILS/VIPsystem/app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_people, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @peoples = People.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @people = People.new
    @office = office_atr
    @security = security_atr
  end

  # GET /people/1/edit
  def edit
    @office = office_atr
    @security = security_atr
  end

  # POST /people
  # POST /people.json
  def create
    @people = People.new(people_params)

    respond_to do |format|
      if @people.save
        format.html { redirect_to root_path, notice: 'Um VIP ' + @people.name.to_s + ' foi criado com sucesso!' }
        format.json { render :show, status: :created, location: @people }
      else
        format.html { render :new }
        format.json { render json: @people.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @people.update(people_params)
        format.html { redirect_to root_path(@people), notice: 'VIP  ' + @people.name.to_s + ' foi atualizado com sucesso!' }
        format.json { render :show, status: :ok, location: @people }
      else
        format.html { render :edit }
        format.json { render json: @people.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @people.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Um VIP ' + @people.name.to_s + ' foi deletado com sucesso!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_people
      @people = People.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def people_params
      params.require(:people).permit(:name, :cpf, :cellPhone, :borned, :office, security:[])
    end

    def office_atr
      ["Governador","Presidente","General", "Outros"]
    end

    def security_atr
      {"Aproximada" => 1, "Combio" => 2, "Batedor" => 3, "Helicóptero" => 4, "F.E." => 5}
    end
end

RAILS/VIPsystem/app/helpers/application_helper.rb
module ApplicationHelper
end

RAILS/VIPsystem/app/helpers/people_helper.rb
module PeopleHelper
	def checked(area)
		@people.security.nil? ? false : @people.security.match(area)
	end
end

RAILS/VIPsystem/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VIPsystem</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
</head>
<body>
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
      <%= yield %>
    </div>
    <div class="col-md-2"></div>
  </div>
</body>
</html>

RAILS/VIPsystem/app/views/people/_form.html.erb
<%= form_for :people do |f| %>
  <% if @people.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@people.errors.count, "error") %> prohibited this people from being saved:</h2>

      <ul>
      <% @people.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div id="container-fluid" class="row form-bottom">
    <div class="row">
      <div class="control-group">
        <div class="form-group col-xs-12 floating-label-form-group controls">
          <%= f.text_field :name , :type => 'text' , :class => 'form-control' , :placeholder => 'Nome' , :id => 'name' , :required => true %>
          <p class="help-block text-danger"></p>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-4">
        <div class="control-group">
          <div class="form-group col-xs-12 floating-label-form-group controls">
            <%= f.text_field :cpf , :type => 'text' , :class => 'form-control' , :placeholder => 'CPF' , :id => 'CPF', pattern: ".{14,}" , :required => true %>
            <p class="help-block text-danger"></p>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="control-group">
          <div class="form-group col-xs-12 floating-label-form-group controls">
            <%= f.text_field :cellPhone , :type => 'text' , :class => 'form-control' , :placeholder => 'Celular' , :id => 'cellPhone', pattern: ".{15,}" , :required => true %>
            <p class="help-block text-danger"></p>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="control-group">
          <div class="form-group col-xs-12 floating-label-form-group controls">
            <%= f.text_field :borned , :type => 'text' , :class => 'form-control borned' , :placeholder => 'Data de Nascimento' , :id => 'borned', pattern: ".{10,}" , :required => true %>
            <p class="help-block text-danger"></p>
          </div>
        </div>    
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <% @office.each do |value| %>
          <%= f.radio_button :office, value, :required => true%><%= value %>
        <% end %>
      </div>
      <div class="col-md-6">
        <%= check_box_tag  'people[security][]', 'Combio', checked('Combio'), id: 'security_combio' %>
        <%= label_tag 'people_combio', 'Combio' %>
        <%= check_box_tag  'people[security][]', 'Batedor', checked('Batedor'), id: 'security_batedor' %>
        <%= label_tag 'people_combio', 'Batedor' %>
        <%= check_box_tag  'people[security][]', 'F.E.', checked('F.E.'), id: 'security_fe' %>
        <%= label_tag 'people_combio', 'F.E.' %>
        <%= check_box_tag  'people[security][]', 'Aproximada', checked('Aproximada'), id: 'security_aproximada' %>
        <%= label_tag 'people_combio', 'Aproximada' %>
      </div>
    </div>
    <div id="row">
      <div id="success"></div>
        <%= f.submit "Adicionar", :type => "submit" , :class => "btn btn-success btn-lg"%>
      </div>
    </div>
  </div>
<% end %>

RAILS/VIPsystem/app/views/people/edit.html.erb
</br>
<div class="row form-top">
  <h3 class="text-md-center">Editar VIP</h3>
</div>

<%= render 'form' %>

RAILS/VIPsystem/app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h2 class="text-md-center">Lista dos VIPs</h2>

<table class="table table-hover">
  <thead>
    <tr>
      <th><strong>Nome</strong></th>
      <th><strong>CPF</strong></th>
      <th><strong>Celular</strong></th>
      <th><strong>Data de Nascimento</strong></th>
      <th><strong>Tipo</strong></th>
      <th><strong>Segurança</strong></th>
      <th class="text-md-center"><%= link_to new_person_path do %><span class="btn btn-success"><i class="fa fa-plus" aria-hidden="true"></i></span><% end %></th>
    </tr>
  </thead>
  <tbody>
    <% @peoples.each do |f|%>
      <tr>
        <td><%= f.name %></td>
        <td><%= f.cpf %></td>
        <td><%= f.cellPhone %></td>
        <td><%= f.borned %></td>
        <td><%= f.office %></td>
        <td><%= f.security %></td>
        <td>
          <div class="text-md-center">
            <%= link_to edit_person_path(f) do %><div class="btn btn-warning"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></div><% end %>

            <%= link_to person_path(f), :method => :delete, data: {confirm: "Tem certeza que deseja deletar?"} do %> <div class="btn btn-danger"><i class="fa fa-times" aria-hidden="true"></i></div><% end %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

RAILS/VIPsystem/app/views/people/new.html.erb
</br>
<div class="row form-top">
	<h3 class="text-md-center">Novo VIP</h3>
</div>

<%= render 'form' %>

RAILS/VIPsystem/app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @person.cpf %>
</p>

<p>
  <strong>Cellphone:</strong>
  <%= @person.cellPhone %>
</p>

<p>
  <strong>Borned:</strong>
  <%= @person.borned %>
</p>

<p>
  <strong>Office:</strong>
  <%= @person.office %>
</p>

<p>
  <strong>Security:</strong>
  <%= @person.security %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>