RAILS/VIP/config/routes.rb
Rails.application.routes.draw do
  root 'peoples#index'
  resources :peoples
  post "peoples/:id/edit" => "peoples#update"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

RAILS/VIP/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

RAILS/VIP/app/models/people.rb
class People < ApplicationRecord
	validates :name, :cpf, :borned, presence: true
end

RAILS/VIP/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

RAILS/VIP/app/controllers/peoples_controller.rb
class PeoplesController < ApplicationController
  def index
    @peoples = People.all
  end

  def new
    @people = People.new
    @office = office_atr
    @security = security_atr
  end

  def create
    @people = People.new(people_params)

    respond_to do |format|
      if @people.save
        format.html { redirect_to root_path, notice: 'Um VIP ' + @people.name.to_s + ' foi criado com sucesso!' }
      else
        format.html { render :new }
        format.json { render json: @people.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @people = set_people
    @office = office_atr
    @security = security_atr
  end

  def update
    @people = set_people
    respond_to do |format|
      if @people.update(people_params)
        format.html { redirect_to root_path(@people), notice: 'VIP  ' + @people.name.to_s + ' foi atualizado com sucesso!' }
        format.json { render :show, status: :ok, location: @people }
      else
        format.html { render :edit }
        format.json { render json: @people.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @people = set_people
    name = @people.name
    @people.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Um VIP ' + @people.name.to_s + ' foi deletado com sucesso!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_people
      @people = People.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def people_params
      params.require(:people).permit(:name, :cpf, :cellPhone, :borned, :office, :security)
    end

    def office_atr
      ["Governador","Presidente","General", "Outros"]
    end

    def security_atr
      {"Aproximada" => 1, "Combio" => 2, "Batedor" => 3, "Helicóptero" => 4, "F.E." => 5}
    end
end

RAILS/VIP/app/helpers/peoples_helper.rb
module PeoplesHelper
end

RAILS/VIP/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VIP</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application'%>
    <script type="text/javascript">
      ("#CPF").mask("999.999.999-00")
    </script>
  </head>

  <body>
    <div class="content container">
      <div class="row">
        <div class="col-md-2">
        </div>
        <div class="col-md-8">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

RAILS/VIP/app/views/peoples/edit.html.erb
</br>
<div class="row "> 
  <div class="row form-top">
    <h3 class="text-md-center">Novo VIP</h3>
  </div>
  <%= form_for :people, action: "update", :method => :POST do |f| %>
    <div id="container-fluid" class="row form-bottom">
      <div class="row">
        <div class="control-group">
          <div class="form-group col-xs-12 floating-label-form-group controls">
            <%= f.text_field :name , :type => 'text' , :class => 'form-control' , :placeholder => 'Nome' , :id => 'name' , :required => true %>
            <p class="help-block text-danger"></p>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-4">
          <div class="control-group">
            <div class="form-group col-xs-12 floating-label-form-group controls">
              <%= f.text_field :cpf , :type => 'text' , :class => 'form-control' , :placeholder => 'CPF' , :id => 'CPF' , :required => true %>
              <p class="help-block text-danger"></p>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="control-group">
            <div class="form-group col-xs-12 floating-label-form-group controls">
              <%= f.text_field :cellPhone , :type => 'text' , :class => 'form-control' , :placeholder => 'Celular' , :id => 'cellPhone' , :required => true %>
              <p class="help-block text-danger"></p>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="control-group">
            <div class="form-group col-xs-12 floating-label-form-group controls">
              <%= f.text_field :borned , :type => 'text' , :class => 'form-control borned' , :placeholder => 'Data de Nascimento' , :id => 'borned' , :required => true %>
              <p class="help-block text-danger"></p>
            </div>
          </div>    
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <% @office.each do |value| %>
            <div class='col-md-4'>
              <%= f.radio_button :office, value, :required => true %><%= value %>
            </div>
          <% end %>
        </div>
        <div class="col-md-6">
          <% @security.each do |a_value| %>
            <%= f.check_box(:security, { :multiple => true }, a_value) %><%= a_value%>
          <% end %>
        </div>
      </div>
      <div id="row">
        <div id="success"></div>
          <%= f.submit "Adicionar", :type => "submit" , :class => "btn btn-success btn-lg"%>
        </div>
      </div>
    </div>
  <% end %>
</div>

RAILS/VIP/app/views/peoples/index.html.erb
<%= javascript_tag do %>
  alert("My example alert box.");
<% end %>
<h2 class="text-md-center">Lista dos VIPs</h2>

<table class="table table-hover">
  <thead>
    <tr>
      <th><strong>Nome</strong></th>
      <th><strong>CPF</strong></th>
      <th><strong>Celular</strong></th>
      <th><strong>Data de Nascimento</strong></th>
      <th><strong>Tipo</strong></th>
      <th><strong>Segurança</strong></th>
      <th class="text-md-center"><%= link_to new_people_path do %><span class="btn btn-success"><i class="fa fa-plus" aria-hidden="true"></i></span><% end %></th>
    </tr>
  </thead>
  <tbody>
    <% @peoples.each do |f|%>
      <tr>
        <td><%= f.name %></td>
        <td><%= f.cpf %></td>
        <td><%= f.cellPhone %></td>
        <td><%= f.borned %></td>
        <td><%= f.office %></td>
        <td><%= f.security %></td>
        <td>
          <%= link_to edit_people_path(f) do %><div class="btn btn-warning"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></div><% end %>
          <%= link_to people_path(f), :method => :delete, data: {confirm: "Tem certeza que deseja deletar?"} do %> <div class="btn btn-danger"><i class="fa fa-times" aria-hidden="true"></i></div><% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

RAILS/VIP/app/views/peoples/new.html.erb
</br>
<div class="row "> 
  <div class="row form-top">
    <h3 class="text-md-center">Novo VIP</h3>
  </div>
  <%= form_for :people, url: { action: "create" } do |f| %>
    <div id="container-fluid" class="row form-bottom">
      <div class="row">
        <div class="control-group">
          <div class="form-group col-xs-12 floating-label-form-group controls">
            <%= f.text_field :name , :type => 'text' , :class => 'form-control' , :placeholder => 'Nome' , :id => 'name' , :required => true %>
            <p class="help-block text-danger"></p>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-4">
          <div class="control-group">
            <div class="form-group col-xs-12 floating-label-form-group controls">
              <%= f.text_field :cpf , :type => 'text' , :class => 'form-control' , :placeholder => 'CPF' , :id => 'CPF' , :required => true %>
              <p class="help-block text-danger"></p>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="control-group">
            <div class="form-group col-xs-12 floating-label-form-group controls">
              <%= f.text_field :cellPhone , :type => 'text' , :class => 'form-control' , :placeholder => 'Celular' , :id => 'cellPhone' , :required => true %>
              <p class="help-block text-danger"></p>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="control-group">
            <div class="form-group col-xs-12 floating-label-form-group controls">
              <%= f.text_field :borned , :type => 'text' , :class => 'form-control borned' , :placeholder => 'Data de Nascimento' , :id => 'borned' , :required => true %>
              <p class="help-block text-danger"></p>
            </div>
          </div>    
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <% @office.each do |value| %>
            <%= f.radio_button :office, value, :required => true%><%= value %>
          <% end %>
        </div>
        <div class="col-md-6">
          <% @security.each do |key, a_value| %>
            <%= f.check_box(:security, { :multiple => true }, a_value) %><%= key %>
          <% end %>
        </div>
      </div>
      <div id="row">
        <div id="success"></div>
          <%= f.submit "Adicionar", :type => "submit" , :class => "btn btn-success btn-lg"%>
        </div>
      </div>
    </div>
  <% end %>
</div>